# Generated by Django 3.0.7 on 2020-07-07 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='announcements',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='calendar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='communication_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='election_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='election_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='election_start',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='users/images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='school',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.BigIntegerField(default=2020),
        ),
    ]
