# Generated by Django 3.0.7 on 2020-07-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20200707_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
