# Generated by Django 3.0.8 on 2020-07-24 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0007_auto_20200718_0032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='user',
            new_name='speaker',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='user',
            new_name='voter',
        ),
        migrations.RemoveField(
            model_name='position',
            name='candidates',
        ),
        migrations.AddField(
            model_name='position',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Group')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='election',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Election'),
        ),
    ]
