# Generated by Django 3.0.7 on 2020-07-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200710_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='membership',
            name='role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='leadership',
            field=models.BooleanField(default=False),
        ),
    ]
