export default {
    PEOPLE: [
        {profile_id: '1', user: 'Gauth', bio: "My name is Gautham Raju and I am a Junior Web Developer for Oswald Technologies. I am an accomplished coder and programmer, and I enjoy using my skills to contribute to the exciting technological advances that happen every day at Oswald Tech.\n\nI graduated from the California Institute of Technology in 2016 with a Bachelor's Degree in Software Development. While in school, I earned the 2015 Edmund Gains Award for my exemplary academic performance and leadership skills.", 
        accomplishments: ['Business Professionals of America State Leadership Qualifier', 'Health Occupation Students of America International Leadership Conference qualifier'], location: 'Austin', birth_date: '01-01-0101', picture: require('./profile4.jpg'), school: 'UT', year: '2023', interests: ['- None'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '2', user: 'Sethi', bio: 'StormPhoenix', 
        accomplishments: ['Business Professionals of America State Leadership Qualifier', 'Health Ocupation Students of America International Leadership Conference qualifier'], location: 'Austin', birth_date: '01-01-0101', picture: require('./profile3.jpg'), school: 'UT', year: '2023', interests: ['- Warzone', '\n- Piano', '\n- Nico'], additional: '- I am highly intrigued by the applications and nuances of computer science within different industries and its subsequent impact on businesses and newer technologies.'},
        {profile_id: '3', user: 'Dhruv', bio: 'I am Driven with passion for discovering new information and learning new things. I am aspiring to go into the field of Data Science or create a start up with new forms of technology. I am hardworking, social, and responsible with any given task. ', 
        accomplishments: ['Business Professionals of America State Leadership Qualifier', 'Health Ocupation Students of America International Leadership Conference qualifier'], location: 'Dallas', birth_date: '01-01-0101', picture: require('./profile2.jpg'), school: 'UTD', year: '2023', interests: ['- Warzone', '\n- C#'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '4', user: 'Raju', bio: 'Student at The University of Texas at Austin', 
        accomplishments: ['Business Professionals of America State Leadership Qualifier', 'Health Ocupation Students of America International Leadership Conference qualifier'], location: 'Austin', birth_date: '01-01-0101', picture: require('./profile1.png'), school: 'UT', year: '2023', interests: ['- Warzone'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '5', user: 'Ryan Reynolds', bio: 'SIMP', location: 'Hyderabad', birth_date: '01-01-0101', picture: require('./dc.jpg'), school: 'UT', year: '2023', clubBio: "Ryan Rodney Reynolds (born October 23, 1976) is a Canadian-American actor, film producer and entrepreneur. He began his career starring in the Canadian teen soap opera Hillside (1991–1993) and had minor roles before landing the lead role on the sitcom Two Guys and a Girl between 1998 and 2001. \n\nReynolds then starred in a range of films, including comedies such as National Lampoon's Van Wilder (2002), Waiting... (2005), and The Proposal (2009). \n\nHe also performed in dramatic roles in Buried (2010), Woman in Gold (2015), and Life (2017), starred in action films such as Blade: Trinity (2004), Deadpool (2016), and 6 Underground (2019) and provided voice acting in the animated features The Croods and Turbo (2013) and Pokemon: Detective Pikachu (2019)",
        manifesto: "I believe that every child has potential. Regardless of race, socioeconomic class, or IQ, every child has the ability to contribute to our world. It can be intellectual-- the next brilliant math or physics theorem, the next great poem of our time-- it can be athletic-- representing fair play and competition-- it can be artistic-- a song, a dance, a play. \n\nEvery child has potential. No child is confined by where they live, who their parents are, what society expects of them. Every child can contribute something beautiful to our world. It can be a smile, a laugh, one good thought. That is all it takes to change someone's life.",
        achieve: ["Maintained a 97% satisfaction rating over a 24-month period as a customer care representative.",
        "Exceeded retail sales goals by an average of 17% every quarter in 2016.",
        "Cut data processing time by 50% by building a new cloud data infrastructure, leading to more timely insights.",
        "Created a company culture initiative which raised employee satisfaction rates by 25% YoY.",
        "Raised employee retention rates by 15% over a 5-year period by implementing a tiered-interview system and organizing a minimum of 2 team outings per quarter.",
        "Hired and managed a team of 6 data scientists to successfully deploy a new data processing platform ahead of schedule.",
        "Organized the company’s annual international summit, including flights, accommodations, and itineraries for more than 30 attendees."],
        exp: [{title: 'Teens Teach Tennis', role: 'Co-Founder', description: 'Taught children tennis skills while also managing money and marketing.', duration: 'Jun 2017 - Jul 2020'},
        {title: 'Burgerim', role: 'Cashier', description: 'Would greet guests and take their orders upon arrival. Cleaned up the restaurant and delivered food as well.', duration: 'Apr 2019 - Jun 2019', interests: ['Hi', 'hello'], additional: '- Valedictorian at Middle of Nowhere High School'}]},
        {profile_id: '6', user: 'User2', bio: 'SIMP', location: 'Hyderabad', birth_date: '01-01-0101', picture: require('./nhs.png'), school: 'UT', year: '2023', interests: ['Hi', 'hello'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '7', user: 'User3', bio: 'SIMP', location: 'Hyderabad', birth_date: '01-01-0101', picture: require('./nhs.png'), school: 'UT', year: '2023', interests: ['Hi', 'hello'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '8', user: 'User4', bio: 'SIMP', location: 'Hyderabad', birth_date: '01-01-0101', picture: require('./nhs.png'), school: 'UT', year: '2023', interests: ['Hi', 'hello'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '9', user: 'User5', bio: 'SIMP', location: 'Hyderabad', birth_date: '01-01-0101', picture: require('./nhs.png'), school: 'UT', year: '2023', interests: ['Hi', 'hello'], additional: '- Valedictorian at Middle of Nowhere High School'},
        {profile_id: '10', user: 'Cam', bio: 'GOAT', location: 'Austin', birth_date: '01-01-0101', picture: require('./nhs.png'), school: 'UT', year: '2023', interests: ['Hi', 'hello'], additional: '- Valedictorian at Middle of Nowhere High School'},
    ], 

    COLOR: ['#173F5F', '#20639B', '#3CAEA3', '#ED553B'],

    LIVE: [{info:'2020 Officer Elections', started: 'NO', start: 'Aug 18', image: require('./orange.png'), end: 'Aug 18', club: 'Code Orange', user: 'users', startTime: '2020-08-18', index: 0,
    positions: [
        {role: 'President', can: [4, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
        {role: 'Vice President', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
        {role: 'Treasurer', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
        {role: 'Secretary', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
        {role: 'Committee', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
        {role: 'Admin', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}]},

        {info:'ACM Fall Election', started: 'NO', start: 'Aug 18', image: require('./acm.png'), end: 'Aug 18', club: 'ACM', user: 'user-plus', startTime: '2020-08-18', index: 0,
        positions: [
            {role: 'President', can: [4, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
            {role: 'Vice President', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [2, 2, 2, 2]}, 
            {role: 'Treasurer', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 3, 1, 3]}, 
            {role: 'Secretary', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [4, 1, 2, 1]}, 
            {role: 'Committee', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [1, 2, 2, 3]}, 
            {role: 'Admin', can: [0, 1, 2, 3], ind: Math.round(Math.random() * 3), vote: [3, 2, 2, 1]}]}],

        UPCOMING: [{info:'Exec. Council Elections', started: 'NO', start: 'Aug 18', image: require('./ut.png'), club: 'Student Congress', user: 'users', 
        url: 'https://docs.google.com/forms/d/1FE3OKvMuLh-ebOgNA4OqN0r-hrpJRXsLT_uGwW8rfOc/edit?ts=5ed83f58&no_redirect=true',
        positions: [
            {role: 'President', 
            qual: ['Must be at least a junior', 'Must be in the club for at least 2 years', 'Application essay required', '3.0 Minimum GPA', 'Willing to commit 6 hours a week'], 
            spec: ['Ultimately responsible for all aspects of the club', 'Sets direction for the club and events organised',
        'Run club meetings and should be expected to be the primary contact between the club and outside contacts', 'Delegate tasks and roles to other club members', 'Prepare future execs for their roles'], 
        color: '#61a8ff', index: 0}, 
            {role: 'Vice President', 
            qual: ['Must be at least a junior', 'Must be in the club for at least 2 years', 'Application essay required', '3.0 Minimum GPA', 'Willing to commit 6 hours a week'], 
            spec: ['Support the President who will delegate tasks like publicity or event marketing', 
        'Can work productively with the President as hostile relations in the executive can be disruptive for the club', 'Set a positive example to other committee members and help maintain morale'], 
        color: '#FE6C7C', index: 1}, 
            {role: 'Treasurer', 
            qual: ['Attends the club leadership seminar or has experience keeping detailed financial accounts', 'Finance major or 2 years experience in maintaining accounts', 'At least a sophomore'], 
            spec: ['In charge of club finances and grant applications', 'Record all monetary transactions and keep all receipts for the year'], 
            color: '#FE6C7C', index: 2}, 
            {role: 'Secretary', 
            qual: ['Must be at least a junior', 'Must be in the club for at least 2 years', 'Application essay required', '3.0 Minimum GPA', 'Willing to commit 6 hours a week'], 
            spec: ['Notify people of upcoming meetings', 'Take minutes at the meetings', 'Maintain an up to date membership database', 
        'Maintaining the clubs email and Facebook groups', 'Main point of contact between the committee, executive and club members'], 
        color: '#61a8ff', index: 3}, 
            {role: 'Committee', 
            qual: ['Must be at least a sophomore', 'Must be in the club for at least 2 years', 'Application essay required', '3.0 Minimum GPA', 'Willing to commit 6 hours a week'], 
            spec: ["Advise the president on any subject he may require relating to the duties of each member's respective office", 
        'Selling tickets to events', 'Organising club shirts and fundraising activities'],
        color: '#61a8ff', index: 4}, 
            {role: 'Admin', 
            qual: ['Must be knowledgeable about Trefle', 'Must be in the club for at least 1 year', 'Application essay required', '3.0 Minimum GPA', 'Willing to commit 2 hours a week'], 
            spec: ['Tracking club attendance', 'Maintaining club membership lists', 'Keeping members informed through a club newsletter and Trefle', 'Collecting dues'], 
            color: '#FE6C7C', index: 5}]}] 
}