# Generated by Django 3.0.7 on 2020-07-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='users/images')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('year', models.BigIntegerField()),
                ('biography', models.CharField(max_length=350)),
                ('announcements', models.BooleanField(null=True)),
                ('election_start', models.BooleanField(null=True)),
                ('election_creation', models.BooleanField(null=True)),
                ('election_end', models.BooleanField(null=True)),
                ('communication_message', models.BooleanField(null=True)),
                ('communication_group', models.BooleanField(null=True)),
                ('calendar', models.BooleanField(null=True)),
            ],
        ),
    ]
