# Generated by Django 3.0.7 on 2020-06-29 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=100)),
                ('vpresident', models.CharField(max_length=100)),
                ('treasurer', models.CharField(max_length=100)),
                ('secretary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='users/images')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('year', models.BigIntegerField()),
                ('biography', models.CharField(max_length=350)),
                ('announcements', models.BooleanField(null=True)),
                ('election_start', models.BooleanField(null=True)),
                ('election_creation', models.BooleanField(null=True)),
                ('election_end', models.BooleanField(null=True)),
                ('communication_message', models.BooleanField(null=True)),
                ('communication_group', models.BooleanField(null=True)),
                ('calendar', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField(null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.ClubData')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserData')),
            ],
        ),
    ]
