# Generated by Django 3.0.7 on 2020-06-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('year', models.BigIntegerField()),
                ('biography', models.CharField(max_length=350)),
            ],
        ),
    ]
