# Generated by Django 3.0.7 on 2020-06-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='biography',
            field=models.CharField(max_length=250),
        ),
    ]
